version: '3'
services:
  wordpress:
#    container_name: wordpress
#    build:
#      context: ./
#      dockerfile: Dockerfile
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      - ENV=development
      - MYSQL_HOST=mysql
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_PORT=3306
      - DEBUG=false
      - DOMAIN_CURRENT_SITE=wordpress.lvh.me
      - CDN_DOMAIN=wordpress.lvh.me

volumes:
  wordpress:
